"""split models

Revision ID: 1d7de830c209
Revises: 0ac57dd455ab
Create Date: 2025-08-22 10:57:36.404970

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '1d7de830c209'
down_revision = '0ac57dd455ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
