"""fix relationships

Revision ID: 370fdfcbf066
Revises: 67ba49283e65
Create Date: 2025-08-22 13:51:09.596023

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '370fdfcbf066'
down_revision = '67ba49283e65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
