"""initial_schema

Revision ID: 62e9bba9b591
Revises: 6a725f235d06
Create Date: 2025-11-07 18:16:36.880040

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '62e9bba9b591'
down_revision = '6a725f235d06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('module_catalog',
    sa.Column('module_id', sa.Integer(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('current_schema_version', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('module_id')
    )
    op.create_index(op.f('ix_module_catalog_code'), 'module_catalog', ['code'], unique=True)
    op.create_index('module_catalog_module_code', 'module_catalog', ['code'], unique=True)
    op.create_table('structure',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('city', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('postal_code', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('province', sqlmodel.sql.sqltypes.AutoString(length=2), nullable=False),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('fax', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('vat_number', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('fiscal_code', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=True),
    sa.Column('max_capacity', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by_user_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['deleted_by_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_structure_code'), 'structure', ['code'], unique=True)
    op.create_index(op.f('ix_structure_deleted_at'), 'structure', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_structure_name'), 'structure', ['name'], unique=False)
    op.create_table('patient',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('fiscal_code', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('place_of_birth', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('gender', sqlmodel.sql.sqltypes.AutoString(length=1), nullable=False),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('city', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('postal_code', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
    sa.Column('province', sqlmodel.sql.sqltypes.AutoString(length=2), nullable=True),
    sa.Column('health_card_number', sa.Text(), nullable=True),
    sa.Column('emergency_contact_name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('emergency_contact_phone', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('emergency_contact_relationship', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('allergies', sa.JSON(), nullable=True),
    sa.Column('chronic_conditions', sa.JSON(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by_user_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['deleted_by_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patient_deleted_at'), 'patient', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_patient_first_name'), 'patient', ['first_name'], unique=False)
    op.create_index(op.f('ix_patient_fiscal_code'), 'patient', ['fiscal_code'], unique=True)
    op.create_index(op.f('ix_patient_last_name'), 'patient', ['last_name'], unique=False)
    op.create_table('dossiers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('structure_id', sa.Uuid(), nullable=False),
    sa.Column('admission_date', sa.DateTime(), nullable=False),
    sa.Column('discharge_date', sa.DateTime(), nullable=True),
    sa.Column('care_level', sa.Enum('R3', 'R3D', name='carelevel'), nullable=False),
    sa.Column('utente', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('cod_nome', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('cod_cognome', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('cod_dossier_n', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('data_nascita', sa.DateTime(), nullable=True),
    sa.Column('sesso', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by_user_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['deleted_by_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], ),
    sa.ForeignKeyConstraint(['structure_id'], ['structure.id'], ),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dossiers_admission_date'), 'dossiers', ['admission_date'], unique=False)
    op.create_index(op.f('ix_dossiers_care_level'), 'dossiers', ['care_level'], unique=False)
    op.create_index(op.f('ix_dossiers_deleted_at'), 'dossiers', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_dossiers_discharge_date'), 'dossiers', ['discharge_date'], unique=False)
    op.create_index(op.f('ix_dossiers_patient_id'), 'dossiers', ['patient_id'], unique=False)
    op.create_index(op.f('ix_dossiers_structure_id'), 'dossiers', ['structure_id'], unique=False)
    op.create_table('module_entry',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('dossier_id', sa.UUID(), nullable=False),
    sa.Column('module_code', sa.String(length=50), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('data', sa.Text(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by_user_id', sa.UUID(), nullable=True),
    sa.Column('deletion_reason', sa.Text(), nullable=True),
    sa.Column('signature_hash', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['deleted_by_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['dossier_id'], ['dossiers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_module_dossier', 'module_entry', ['dossier_id', 'module_code', 'occurred_at'], unique=False)
    op.create_index(op.f('ix_module_entry_module_code'), 'module_entry', ['module_code'], unique=False)
    op.drop_index('ix_user_structure_id', table_name='user')
    op.create_foreign_key(None, 'user', 'structure', ['structure_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.create_index('ix_user_structure_id', 'user', ['structure_id'], unique=False)
    op.drop_index(op.f('ix_module_entry_module_code'), table_name='module_entry')
    op.drop_index('idx_module_dossier', table_name='module_entry')
    op.drop_table('module_entry')
    op.drop_index(op.f('ix_dossiers_structure_id'), table_name='dossiers')
    op.drop_index(op.f('ix_dossiers_patient_id'), table_name='dossiers')
    op.drop_index(op.f('ix_dossiers_discharge_date'), table_name='dossiers')
    op.drop_index(op.f('ix_dossiers_deleted_at'), table_name='dossiers')
    op.drop_index(op.f('ix_dossiers_care_level'), table_name='dossiers')
    op.drop_index(op.f('ix_dossiers_admission_date'), table_name='dossiers')
    op.drop_table('dossiers')
    op.drop_index(op.f('ix_patient_last_name'), table_name='patient')
    op.drop_index(op.f('ix_patient_fiscal_code'), table_name='patient')
    op.drop_index(op.f('ix_patient_first_name'), table_name='patient')
    op.drop_index(op.f('ix_patient_deleted_at'), table_name='patient')
    op.drop_table('patient')
    op.drop_index(op.f('ix_structure_name'), table_name='structure')
    op.drop_index(op.f('ix_structure_deleted_at'), table_name='structure')
    op.drop_index(op.f('ix_structure_code'), table_name='structure')
    op.drop_table('structure')
    op.drop_index('module_catalog_module_code', table_name='module_catalog')
    op.drop_index(op.f('ix_module_catalog_code'), table_name='module_catalog')
    op.drop_table('module_catalog')
    # ### end Alembic commands ###
