"""fix relationships

Revision ID: 6a725f235d06
Revises: 370fdfcbf066
Create Date: 2025-08-22 13:55:41.427482

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '6a725f235d06'
down_revision = '370fdfcbf066'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
