"""adding status in dossier

Revision ID: 7f2f633549b3
Revises: b4808d25854a
Create Date: 2025-11-10 11:32:46.834086

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '7f2f633549b3'
down_revision = 'b4808d25854a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dossiers', sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.create_index(op.f('ix_dossiers_status'), 'dossiers', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dossiers_status'), table_name='dossiers')
    op.drop_column('dossiers', 'status')
    # ### end Alembic commands ###
