"""cose2

Revision ID: 8041607397cc
Revises: 98aee87c3fd3
Create Date: 2025-11-10 09:01:17.565550

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '8041607397cc'
down_revision = '98aee87c3fd3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role', sa.Column('modules', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('role', 'modules')
    # ### end Alembic commands ###
