"""cose

Revision ID: 98aee87c3fd3
Revises: c898397f78a8
Create Date: 2025-11-10 08:59:37.988133

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '98aee87c3fd3'
down_revision = 'c898397f78a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('audit_log', 'ts',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('module_entry', 'occurred_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('module_entry', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False)
    op.alter_column('module_entry', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('module_entry', 'deletion_reason',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.add_column('role', sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True))
    op.drop_constraint('role_created_by_user_id_fkey', 'role', type_='foreignkey')
    op.drop_column('role', 'created_by_user_id')
    op.drop_column('role', 'modules')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role', sa.Column('modules', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('role', sa.Column('created_by_user_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('role_created_by_user_id_fkey', 'role', 'user', ['created_by_user_id'], ['id'])
    op.drop_column('role', 'description')
    op.alter_column('module_entry', 'deletion_reason',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('module_entry', 'deleted_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('module_entry', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('module_entry', 'occurred_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    op.alter_column('audit_log', 'ts',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
    # ### end Alembic commands ###
