"""cambiato il nome alla colonna creato da in role

Revision ID: c898397f78a8
Revises: 658f10fef3f2
Create Date: 2025-11-10 08:15:57.726295

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'c898397f78a8'
down_revision = '658f10fef3f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role', sa.Column('created_by_user_id', sa.Uuid(), nullable=True))
    op.drop_constraint('role_created_by_fkey', 'role', type_='foreignkey')
    op.create_foreign_key(None, 'role', 'user', ['created_by_user_id'], ['id'])
    op.drop_column('role', 'created_by')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role', sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'role', type_='foreignkey')
    op.create_foreign_key('role_created_by_fkey', 'role', 'user', ['created_by'], ['id'])
    op.drop_column('role', 'created_by_user_id')
    # ### end Alembic commands ###
